# Generated by Django 3.0.2 on 2020-03-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=125)),
                ('pagina_web', models.URLField(blank=True, max_length=125)),
                ('direccion', models.TextField(blank=True, max_length=500)),
                ('licencia', models.CharField(choices=[('DEMO', 'Demostracion'), ('FULL', 'Full Licencia')], default='DEMO', max_length=100)),
                ('fecha_inicio_demo', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_demo', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=125)),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGESO', 'En Progreso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.Empresa')),
            ],
        ),
    ]
