# Generated by Django 3.0.2 on 2020-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug_identificador',
            field=models.SlugField(default='TEST', max_length=20),
        ),
    ]
