# Generated by Django 3.0.2 on 2020-03-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_empresa_slug_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=100),
        ),
    ]
