# Generated by Django 3.0.2 on 2020-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20200325_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slug_identificador',
            field=models.SlugField(default='test', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('asesor', 'secuencia', 'fecha'), name='turno_unico'),
        ),
    ]
